const mongoose = require('mongoose');

/**
 * Summary Model
 * Stores all summary types, exam cram notes, key points, and chapters
 * generated by Gemini for a given document.
 */
const summarySchema = new mongoose.Schema(
  {
    documentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Document',
      required: true,
      index: true,
    },
    quickSummary: {
      type: String,
      default: '',
    },
    detailedSummary: {
      type: String,
      default: '',
    },
    examNotes: {
      type: String,
      default: '',
    },
    keyPoints: {
      type: mongoose.Schema.Types.Mixed,
      default: [],
    },
    chapters: {
      type: mongoose.Schema.Types.Mixed,
      default: [],
    },
    generatedAt: {
      type: Date,
      default: Date.now,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Summary', summarySchema);
